apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-secret
  labels:
    app: postgres
data:
  POSTGRES_DB: database
  POSTGRES_USER: suser
  POSTGRES_PASSWORD: spassword
  PGDATA: /var/lib/postgresql/data/pgdata
  REDMINE_DB_POSTGRES: database
  REDMINE_DB_USERNAME: suser
  REDMINE_DB_PASSWORD: spassword
  REDMINE_DB_DATABASE: database
  REDMINE_SECRET_KEY_BASE: supersecretkey