apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-volume-claim
  labels:
    app: postgres
spec:
  storageClassName: csi-ceph-ssd-gz1-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi