apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1VENDQWMyZ0F3SUJBZ0lSQUwyamQ3SlEyVVJFdnJNQUJTTXMrY3N3RFFZSktvWklodmNOQVFFTEJRQXcKR2pFWU1CWUdBMVVFQXd3UGEzVmlaWEl0WTJ4MWMzUmxjaTB4TUI0WERUSXpNRFF4TnpJd01qZzBPRm9YRFRJNApNRFF4TmpJd01qZzBPRm93R2pFWU1CWUdBMVVFQXd3UGEzVmlaWEl0WTJ4MWMzUmxjaTB4TUlJQklqQU5CZ2txCmhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBNDNhSkVYRlBRVmg1em1QQVlPTHpwd0l5Y2QzRnBCNEQKdWp4TEZkUjlRSWk4UkdpUU5aUTAxS0VrQkNqL203VUVnOUQ0RUF6ZXlPL2JzSUdQempLMjJ1TTg1ejcxSUc1MQp3Q05Sa0lXSC9ldTg0K2Q1R2ZWSWdmSThnTTFYUlVpamlGZnB2b2hISFhsaGhqVC9lM1pabUxaTFVBelhUYkRGClJyZVIwS280Ni95dVl2TzJ5cVBkR05wL2xjMVRXUGRQL3VQQThYOUcrWkhQdEFTTGx1S1hhQzVKbE9qekE5UDUKVGU5bWxVZG92cDJvendRSjJYV2NLYTNqSThSSGtOeTFxdW9pUkQ0bFhSRitxNXB2TVFXQXFDWk1odUEzMmVvNgpmYkN1S2xmRFpuVzAxRXNlb1pZZFJjYzdPMXcwU1RWd1pjRi9BOEg3WHVrVG1zNXZuQ0xaWHdJREFRQUJveVl3CkpEQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQTRHQTFVZER3RUIvd1FFQXdJQ0JEQU5CZ2txaGtpRzl3MEIKQVFzRkFBT0NBUUVBUUFsbXQzUjFGZkJxczh5SE1lQ1BsdjZTWTRta1Z4b1FoY3hYN2grQWFGNHRDa1N3MUR2ZwpML291Q2ZzVk5zQlBGeEkwRHdEMlRXSVcxajRVVkV4T0MrbitUMW1uSjlyQ25yZ0d1NXhrQ0xpMitqcFRieStDClI4UzhVQTVDQVpiUGJ5S3JabE1IKzU0S0podnB4bmtjZzIrL1pvOWVyUldLcHNBYjhMMVRYR0YxaUZiWlVXMTkKczNCUCthWXl6b29iRzR6dlZxZmk5N3JXNWtEUllpQ3pCQTY0WGc4a2xXNzB5UGg1MFVrK2hlakFmL0ZINExMQgovS2dtZ0RmRlNWWDlYM1hpUkNNcjY0RzlaY1BzRjhTNVJULzBEUEsrSDk5MEl3bTZOVnphZmx3bzYwbDN0c2xYCmMxdHZHdHA1ZjFEZlFpWEFMa0RaWDlpeG1qWERVbUJuM0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://185.86.147.37:6443
  name: kuber-cluster-1
contexts:
- context:
    cluster: kuber-cluster-1
    user: kuber-cluster-1
  name: default/kuber-cluster-1
current-context: default/kuber-cluster-1
kind: Config
preferences: {}
users:
- name: kuber-cluster-1
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: client-keystone-auth
      env:
      - name: "OS_AUTH_URL"
        value: "https://infra.mail.ru:35357/v3/"
      - name: "OS_USERNAME"
        value: "berezin.mihail@gmail.com"
      - name: "OS_PASSWORD"
        value: "t$QIg(i=)UPm3Ke0"
      - name: "OS_PROJECT_ID"
        value: "8e8bbb7975424f1fa6b68c759732b56e"
      - name: "OS_DOMAIN_NAME"
        value: "users"
      interactiveMode: IfAvailable
      provideClusterInfo: false