apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-secret
  labels:
    app: postgres
data:
  POSTGRES_DB: testdatabase
  POSTGRES_USER: testuser
  POSTGRES_PASSWORD: testpasswordapp
  PGDATA: /var/lib/postgresql/data/pgdata